/**
 * Phase 4.3 — comments linked to a community.
 *
 * Drives the API directly for the post step (the chapter composer is well
 * covered by comments.cy.ts and exercising it here would mostly be paint
 * timing). UI rendering is asserted by visiting /communities/[slug] and
 * by checking the chapter view shows the community badge on the comment.
 */

import users from "../fixtures/users.json";

const VERSE = {
  abbrev: "gn",
  chapter: 1,
  verseNumber: 1,
  text: "No princípio criou Deus os céus e a terra.",
  reference: "Gênesis 1:1",
};
const BOOK = {
  abbrev: "gn",
  name: "Gênesis",
  chapters: 50,
  testament: "old",
  group: "pentateuco",
  author: "Moisés",
};
const LONG_TEXT =
  "Esse versículo é o ponto de partida de toda a Escritura e revela a soberania de Deus sobre a criação inteira — céus, terra, tempo, espaço e matéria começam aqui sob Sua palavra. ".repeat(
    2,
  );

/**
 * Resolve the persisted verse's ObjectId — the POST route on
 * /api/comments/[id] expects the verse _id, not a slug. Cypress seeds
 * the verse via cy.seedDb but the id is generated by Mongo so we look
 * it up at runtime.
 */
function fetchVerseId(): Cypress.Chainable<string> {
  return cy
    .request("GET", `/api/books/${VERSE.abbrev}/verses/${VERSE.chapter}`)
    .then((res) => {
      const list = res.body as Array<{ _id: string; verseNumber: number }>;
      const v = list.find((x) => x.verseNumber === VERSE.verseNumber);
      expect(v, "seeded verse").to.exist;
      return v!._id;
    });
}

describe("Comments tagged with a community (Phase 4.3)", () => {
  beforeEach(() => {
    cy.resetDb();
    cy.seedDb({
      users: [
        // Mark the chapter tutorial done so the welcome overlay does not
        // cover the badge we're asserting on.
        { ...users.alice, tutorialsCompleted: ["chapter-v1"] },
        { ...users.bob, tutorialsCompleted: ["chapter-v1"] },
      ],
      books: [BOOK],
      verses: [VERSE],
    });
  });

  it("member can post a comment into a community and the badge shows on the verse", () => {
    cy.loginAs(users.alice.email, users.alice.password);
    // alice creates "reformados" and is auto-creator (but not auto-member,
    // mirror of social platforms — confirm by joining explicitly).
    cy.request("POST", "/api/communities", {
      slug: "reformados",
      name: "Reformados",
      description: "",
    });
    cy.request("POST", "/api/communities/reformados/join");

    fetchVerseId().then((verseId) => {
      cy.request("POST", `/api/comments/${verseId}`, {
        text: LONG_TEXT,
        tags: ["devocional"],
        communitySlug: "reformados",
      }).then((res) => {
        expect(res.status).to.eq(201);
        expect(res.body.communitySlug).to.eq("reformados");
      });
    });

    cy.visit(`/chapter/${VERSE.abbrev}/${VERSE.chapter}`);
    // The verse list <li> uses id={verseNumber}; click the inner button.
    cy.get("li#1 button").first().click();
    cy.get(`[data-testid="comment-community-badge-reformados"]`, { timeout: 8000 }).should(
      "be.visible",
    );
  });

  it("non-member is rejected by the API with 403", () => {
    cy.loginAs(users.alice.email, users.alice.password);
    cy.request("POST", "/api/communities", {
      slug: "reformados",
      name: "Reformados",
      description: "",
    });
    // alice creates it but does NOT join.
    fetchVerseId().then((verseId) => {
      cy.request({
        method: "POST",
        url: `/api/comments/${verseId}`,
        body: {
          text: LONG_TEXT,
          tags: ["devocional"],
          communitySlug: "reformados",
        },
        failOnStatusCode: false,
      }).then((res) => {
        expect(res.status).to.eq(403);
      });
    });
  });

  it("community detail page lists comments posted into it", () => {
    cy.loginAs(users.alice.email, users.alice.password);
    cy.request("POST", "/api/communities", {
      slug: "reformados",
      name: "Reformados",
      description: "",
    });
    cy.request("POST", "/api/communities/reformados/join");
    fetchVerseId().then((verseId) => {
      cy.request("POST", `/api/comments/${verseId}`, {
        text: LONG_TEXT,
        tags: ["devocional"],
        communitySlug: "reformados",
      });
    });

    cy.visit("/communities/reformados");
    cy.get('[data-testid="community-comments"]').should("be.visible");
    cy.contains('[data-testid^="community-comment-"]', "Gênesis 1:1").should(
      "be.visible",
    );
    cy.contains('[data-testid^="community-comment-"]', "@alice").should("be.visible");
  });

  it("API /api/communities/[slug]/comments paginates", () => {
    cy.loginAs(users.alice.email, users.alice.password);
    cy.request("POST", "/api/communities", {
      slug: "reformados",
      name: "Reformados",
      description: "",
    });
    cy.request("POST", "/api/communities/reformados/join");
    fetchVerseId().then((verseId) => {
      cy.request("POST", `/api/comments/${verseId}`, {
        text: LONG_TEXT,
        tags: ["devocional"],
        communitySlug: "reformados",
      });
    });

    cy.request("GET", "/api/communities/reformados/comments").then((res) => {
      expect(res.status).to.eq(200);
      expect(res.body.items).to.have.length(1);
      expect(res.body.items[0].communitySlug).to.eq("reformados");
      expect(res.body.total).to.eq(1);
    });
  });
});
