/**
 * SEO surface — robots, sitemap, page metadata.
 *
 * Generated by Next.js's app/robots.ts, app/sitemap.ts, and the
 * generateMetadata() exports in individual pages.
 */

import users from "../fixtures/users.json";
import bookFixture from "../fixtures/book-gn.json";

describe("SEO", () => {
  beforeEach(() => {
    cy.resetDb();
    cy.seedDb({
      users: [users.alice],
      books: [bookFixture.book],
      verses: bookFixture.verses,
    });
  });

  describe("/robots.txt", () => {
    it("returns text/plain with the standard directives", () => {
      cy.request("/robots.txt").then((res) => {
        expect(res.status).to.eq(200);
        expect(res.headers["content-type"]).to.match(/^text\/plain/);
        const body = res.body as string;
        expect(body).to.match(/User-Agent:\s*\*/i);
        expect(body).to.include("Allow: /");
        expect(body, "auth-gated routes must be in Disallow").to.match(/Disallow:\s*\/api\//);
        expect(body, "admin must be in Disallow").to.match(/Disallow:\s*\/admin/);
        expect(body, "must reference the sitemap").to.match(/Sitemap:\s*https?:\/\/[^\s]+\/sitemap\.xml/);
      });
    });
  });

  describe("/sitemap.xml", () => {
    it("returns XML containing static + chapter URLs", () => {
      cy.request("/sitemap.xml").then((res) => {
        expect(res.status).to.eq(200);
        expect(res.headers["content-type"]).to.match(/xml/);
        const body = res.body as string;

        // Static pages.
        expect(body).to.match(/<loc>[^<]+\/<\/loc>/);
        expect(body).to.match(/<loc>[^<]+\/login<\/loc>/);
        expect(body).to.match(/<loc>[^<]+\/help<\/loc>/);

        // Chapter URLs derived from seeded books. Genesis has 50
        // chapters in the fixture, so /verses/gn/1 ... /verses/gn/50
        // should all be present.
        expect(body).to.match(/<loc>[^<]+\/verses\/gn\/1<\/loc>/);
        expect(body).to.match(/<loc>[^<]+\/verses\/gn\/50<\/loc>/);
      });
    });
  });

  describe("Root layout metadata", () => {
    it("/ has OpenGraph tags and Portuguese locale", () => {
      cy.request("/").then((res) => {
        const html = res.body as string;
        expect(html).to.match(/<meta\s+property="og:title"/i);
        expect(html).to.match(/<meta\s+property="og:type"\s+content="website"/i);
        expect(html).to.match(/<meta\s+property="og:locale"\s+content="pt_BR"/i);
        expect(html).to.match(/<html\s+lang="pt-BR"/i);
      });
    });
  });

  describe("Chapter page metadata (auth-gated)", () => {
    it("Gn 1 returns a metadata-rich title even though the page redirects to /login", () => {
      // generateMetadata() runs server-side BEFORE the auth() check that
      // redirects unauthenticated visitors. Crawlers that fetch the URL
      // directly should still see a proper title and OG tags in the
      // response body, even if the rendered page is a redirect.
      cy.request({
        url: "/verses/gn/1",
        followRedirect: false,
        failOnStatusCode: false,
      }).then((res) => {
        const html = (res.body as string) ?? "";
        // Either the redirect carried the metadata in the original
        // payload, or following the redirect lands on /login. Either
        // way, the public surface should advertise the chapter title
        // somewhere — we check the eventual response body that a crawler
        // would index.
        if (typeof html === "string" && html.length > 0) {
          // Title may appear in <title> or meta og:title.
          const matches =
            /<title>[^<]*Gênesis[^<]*<\/title>/i.test(html) ||
            /<meta\s+property="og:title"\s+content="[^"]*Gênesis/i.test(html);
          expect(matches, "Gênesis should appear in title or og:title").to.be.true;
        }
      });
    });
  });
});
